/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mvgsuyxojoyliznlpdlu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12Z3N1eXhvam95bGl6bmxwZGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1OTg5MDUsImV4cCI6MjA4MjE3NDkwNX0.UmpNmoaKGr_VIUenb7kHD-eomb7jgdHWB7lv-snAcQ8"